[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps --resolve-matrix-from-file && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps --resolve-matrix-from-file"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
