[build]
  base = "frontend"
  command = "cp .env.sepolia .env && npm install --legacy-peer-deps --resolve-matrix-from-file && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps --resolve-matrix-from-file"
  REACT_APP_NETWORK = "sepolia"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
